name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        GOOS: [linux, darwin, windows]
        GOARCH: [amd64, arm64]
        include:
          - GOOS: linux
            GOARCH: arm
    runs-on: ubuntu-latest
    name: Build for ${{ matrix.GOOS }} ${{ matrix.GOARCH }}
    env:
      GOOS: ${{ matrix.GOOS }}
      GOARCH: ${{ matrix.GOARCH }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Install dependencies
        run: go get -v .

      - name: Build
        run: go build -v .

      - name: Export as artifact
        uses: actions/upload-artifact@v4
        with:
          name: devcleaner-${{ matrix.GOOS }}-${{ matrix.GOARCH }}${{ matrix.GOOS == 'windows' && '.exe' || ''}}
          path: devcleaner-go${{ matrix.GOOS == 'windows' && '.exe' || ''}}
